-- Hyprland config (originally autogenerated, hand-edited afterwards)
--
-- Loaded via dofile() from the Home Manager generated hyprland.lua, after that file
-- already ran hl.config for the general/decoration border and shadow colours, the
-- input keyboard and touchpad options, hl.monitor and hl.plugin.load -- none of
-- those are repeated here

-------------
-- PROGRAMS --
-------------

local terminal = "kitty"
local fileManager = "thunar"
-- HUIX.menu is set by the generated file, from rokokol.hyprland.menuCommand
local tabsNum = 4
local getScreen = 'grim -g "$(slurp -b ffffff66 -w 1 && sleep 0.2)"'

-- The wheel cycles through the tab workspaces 1..tabsNum: the workspace that is offset
-- steps away from the active one, wrapping around. A function, so the active workspace
-- is read at press time and no shell is spawned
local function tab(offset, dispatcher)
    return function()
        local id = hl.get_active_workspace().id
        local target = tostring(((id - 1 + offset) % tabsNum) + 1)
        hl.dispatch(dispatcher(target))
    end
end
local function focusWorkspace(target)
    return hl.dsp.focus({ workspace = target })
end
local function moveToWorkspace(target)
    return hl.dsp.window.move({ workspace = target })
end

---------------
-- AUTOSTART --
---------------

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
    hl.exec_cmd("systemctl --user start swayosd.service")

    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon -q >/dev/null 2>&1")
    -- the mako package ships a Type=dbus unit -- a bare "mako" would take the bus
    -- name outside systemd
    hl.exec_cmd("systemctl --user start mako.service")
    hl.exec_cmd("wl-paste --type text --watch cliphist store -max-items 500 store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store -max-items 1000 store")
    hl.exec_cmd("dex -a")
    hl.exec_cmd("super-productivity")
    -- fixes a broken software cursor: a round trip through software cursors
    hl.exec_cmd(
        "hyprctl eval 'hl.config({ cursor = { no_hardware_cursors = 1 } })' && "
            .. "hyprctl eval 'hl.config({ cursor = { no_hardware_cursors = 0 } })'"
    )

    -- also runs on every reload below (config.reloaded), like the original
    -- "exec = ..." line, which unlike "exec-once" fires again on every reload
    hl.exec_cmd(HUIX.scripts .. "/toggle-theme.sh --sync")
end)

-- runs on every reload, mirroring the original plain "exec = ..." line; see the
-- comment at the end of the hyprland.start handler above for why it is in both
hl.on("config.reloaded", function()
    hl.exec_cmd(HUIX.scripts .. "/toggle-theme.sh --sync")
end)

-----------------------------
-- ENVIRONMENT VARIABLES --
-----------------------------

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GTK_CSD", "0")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

hl.config({
    cursor = {
        -- 0 disables hardware cursors outright (the hyprlang value was the
        -- boolean "false"; the Lua option is documented as an int, 0 - 2)
        no_hardware_cursors = 0,
    },
})

-----------------
-- PERMISSIONS --
-----------------

-- permission changes require a Hyprland restart and don't apply on the fly
-- (for security reasons)

-- hl.config({ ecosystem = { enforce_permissions = true } })

hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", mode = "allow" })
hl.permission({
    binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland",
    type = "screencopy",
    mode = "allow",
})
-- hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", mode = "ask" })

------------------
-- APPEARANCE --
------------------

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,

        border_size = 2,

        -- border colours come from the palette, set before this file is loaded

        -- true -- resize windows by dragging their borders and gaps
        resize_on_border = false,

        -- read https://wiki.hypr.land/Configuring/Tearing/ before enabling
        allow_tearing = false,

        layout = "dwindle",
    },
})

hl.config({
    decoration = {
        rounding = 7,
        rounding_power = 2,

        -- opacity of the active and inactive window
        active_opacity = 1.0,
        inactive_opacity = 0.95,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            -- colour set before this file is loaded
        },

        blur = {
            enabled = true,
            size = 3,
            passes = 1,

            vibrancy = 0.1696,
        },
    },
})

hl.config({
    animations = {
        -- "enabled = yes, please :)" in the old config is just true
        enabled = true,
    },
})

-- default curves
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- default animations
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- "smart gaps" / "no gaps when there's a single window" -- uncomment if desired
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding = 0,
-- })
-- hl.window_rule({
--     name = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding = 0,
-- })

hl.config({
    dwindle = {
        preserve_split = true, -- usually what you want
        -- a dragged window lands on the side of the target the cursor is over,
        -- not only in the gaps
        precise_mouse_move = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    misc = {
        force_default_wallpaper = 2, -- 0 or 1 -- disable the mascot wallpaper
        disable_hyprland_logo = false, -- true -- remove the random Hyprland logo/anime girl
        -- if the locker died without releasing the lock (hyprlock crash), let a new
        -- instance lock the session again -- otherwise only a tty is left
        allow_session_lock_restore = true,

        -- hypridle blanks the screen on idle, but waking it back is its on-resume
        -- alone -- let the compositor wake on input too, so a dead hypridle can't
        -- leave a dark screen
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
    },
})

-----------
-- INPUT --
-----------

-- touchpad gestures
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
-- two-finger pinch screen zoom (a live magnifier around the cursor). The
-- mouse_up/mouse_down binds (wheel zoom below) work ONLY with a physical mouse
-- wheel -- on the touchpad scroll binds never fire at all, so on the laptop the
-- zoom is bound to the built-in cursor_zoom gesture (mode live -- continuous
-- while pinching)
hl.gesture({
    fingers = 2,
    direction = "pinch",
    action = "cursor_zoom",
    zoom_level = 1,
    mode = "live",
})

hl.device({
    name = "gaomon-gaomon-tablet_s630",
    output = "DP-1",
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

------------
-- BINDS --
------------

hl.config({
    binds = {
        scroll_event_delay = 0,
    },
})

-- $mainMod = SUPER, $mainScreenMod = SUPER + ALT, inlined into every key string below

-- Core actions
hl.bind("SUPER + Q", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER + E", hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER + V", hl.dsp.window.float())
hl.bind("SUPER + W", hl.dsp.exec_cmd(HUIX.menu))
hl.bind("SUPER + F12", hl.dsp.exec_cmd("loginctl lock-session"))

-- power button -> power menu (logind HandlePowerKey=ignore, see nixos/desktop/logind.nix)
hl.bind("XF86PowerOff", hl.dsp.exec_cmd(HUIX.scripts .. "/rofi-power.sh"), { locked = true })
hl.bind("SUPER + Delete", hl.dsp.exec_cmd(HUIX.scripts .. "/rofi-power.sh"))
hl.bind("SUPER + P", hl.dsp.window.pseudo()) -- dwindle
-- in Hyprland 0.54+ togglesplit moved under layoutmsg
hl.bind("SUPER + T", hl.dsp.layout("togglesplit"))
-- "fullscreen" covers the whole screen; "maximized" would keep the bars, as the
-- old fullscreen action 1 did
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind("SUPER + Z", hl.dsp.exec_cmd("pidof waybar && pkill waybar || waybar"))
hl.bind(
    "SUPER + U",
    hl.dsp.exec_cmd(
        'rofi -modi "ru-en:'
            .. HUIX.scripts
            .. "/rofi-libre.sh ru en,en-ru:"
            .. HUIX.scripts
            .. '/rofi-libre.sh en ru" -show ru-en'
    )
)
hl.bind("SUPER + B", hl.dsp.exec_cmd(HUIX.scripts .. "/rofi-clipboard.sh"))
hl.bind("SUPER + N", hl.dsp.exec_cmd(HUIX.scripts .. "/rofi-notify.sh"))
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd(HUIX.scripts .. "/notify-center.sh dnd toggle"))
hl.bind("SUPER + A", hl.dsp.exec_cmd(HUIX.scripts .. "/toggle-theme.sh"))
-- dictionary and full-screen shaders -- both live in their own flakes, these are
-- just their commands
hl.bind("SUPER + Y", hl.dsp.exec_cmd("rofi-wooordhunt"))
hl.bind("SUPER + SHIFT + G", hl.dsp.exec_cmd("rofi-shader"))
hl.bind("SUPER + G", hl.dsp.exec_cmd("screen-shader effect clear"))
hl.bind("SUPER + CTRL + BackSpace", hl.dsp.exec_cmd("rofi-shader bright reset"))
-- the repeating flag makes dimming feel continuous while the key is held
hl.bind(
    "SUPER + CTRL + bracketright",
    hl.dsp.exec_cmd("rofi-shader bright up"),
    { repeating = true }
)
hl.bind(
    "SUPER + CTRL + bracketleft",
    hl.dsp.exec_cmd("rofi-shader bright down"),
    { repeating = true }
)
hl.bind(
    "SUPER + SHIFT + B",
    hl.dsp.exec_cmd(
        'rofi -show emoji -modi "emoji:rofimoji --action copy --files '
            .. "emojis_smileys_emotion emojis_people_body emojis_animals_nature "
            .. "emojis_food_drink emojis_activities emojis_travel_places emojis_objects "
            .. "emojis_symbols emojis_flags dingbats "
            .. "miscellaneous_symbols_and_pictographs,math:rofimoji --action copy --files "
            .. "math mathematical_operators arrows geometric_shapes greek_and_coptic,"
            .. "chars:rofimoji --action copy --files currency_symbols letterlike_symbols "
            .. "latin-1_supplement general_punctuation superscripts_and_subscripts "
            .. "enclosed_alphanumerics box_drawing cjk_symbols_and_punctuation nerd_font,"
            .. 'kaomoji:rofimoji --action copy --files kaomoji"'
    )
)

-- Screenshots / screen operations
hl.bind("SUPER + ALT + S", hl.dsp.exec_cmd(getScreen .. " - | GTK_THEME=Adwaita:light satty -f -"))
hl.bind("SUPER + ALT + C", hl.dsp.exec_cmd(HUIX.scripts .. "/shot-copy.sh region"))
hl.bind("SUPER + ALT + A", hl.dsp.exec_cmd(HUIX.scripts .. "/pin-screen.sh"))
hl.bind("SUPER + ALT + P", hl.dsp.exec_cmd(HUIX.scripts .. "/colorpicker.sh"))
hl.bind("SUPER + ALT + T", hl.dsp.exec_cmd(HUIX.scripts .. "/ocr.sh rus+eng"))
hl.bind("SUPER + ALT + R", hl.dsp.exec_cmd(HUIX.scripts .. "/ocr.sh rus"))
hl.bind("SUPER + ALT + E", hl.dsp.exec_cmd(HUIX.scripts .. "/ocr.sh eng"))
hl.bind("SUPER + ALT + M", hl.dsp.exec_cmd(HUIX.scripts .. "/shot-copy.sh full"))

-- magnifier / screen zoom with the mouse wheel (ALT+WIN+wheel) -- physical wheel
-- only; on the touchpad the pinch gesture works instead (gesture above)
hl.bind("SUPER + ALT + mouse_down", hl.dsp.exec_cmd(HUIX.scripts .. "/zoom.sh out"))
hl.bind("SUPER + ALT + mouse_up", hl.dsp.exec_cmd(HUIX.scripts .. "/zoom.sh in"))
hl.bind("SUPER + ALT + BackSpace", hl.dsp.exec_cmd(HUIX.scripts .. "/zoom.sh reset"))

-- --- NAVIGATION (FOCUS) ---
-- Move focus (HJKL)
hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }))

-- Move focus (ARROWS)
hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "d" }))

-- --- MOVING WINDOWS ---
-- Move the windows themselves (HJKL) + Shift
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "d" }))

-- Move the windows themselves (ARROWS) + Shift
hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

-- Precise movement of the active window (for floating ones)
hl.bind(
    "SUPER + CTRL + left",
    hl.dsp.window.move({ x = -80, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + CTRL + right",
    hl.dsp.window.move({ x = 80, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + CTRL + up",
    hl.dsp.window.move({ x = 0, y = -80, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + CTRL + down",
    hl.dsp.window.move({ x = 0, y = 80, relative = true }),
    { repeating = true }
)

-- Same for HJKL
hl.bind(
    "SUPER + CTRL + h",
    hl.dsp.window.move({ x = -80, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + CTRL + l",
    hl.dsp.window.move({ x = 80, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + CTRL + k",
    hl.dsp.window.move({ x = 0, y = -80, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + CTRL + j",
    hl.dsp.window.move({ x = 0, y = 80, relative = true }),
    { repeating = true }
)

-- --- WORKSPACES ---
-- Switch workspaces [0-9]
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }))
-- hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))

-- Move a window to workspace [0-9]
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))

-- Special workspace (scratchpad)
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Mouse wheel cycles through the tab workspaces (1..tabsNum)
hl.bind("SUPER + mouse_down", tab(1, focusWorkspace))
hl.bind("SUPER + mouse_up", tab(-1, focusWorkspace))
hl.bind("SUPER + SHIFT + mouse_down", tab(1, moveToWorkspace))
hl.bind("SUPER + SHIFT + mouse_up", tab(-1, moveToWorkspace))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Media keys and brightness
hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd("swayosd-client --output-volume raise"),
    { repeating = true }
)
hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd("swayosd-client --output-volume lower"),
    { repeating = true }
)
hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"),
    { locked = true }
)
hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"),
    { locked = true }
)
hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd("swayosd-client --brightness raise"),
    { repeating = true }
)
hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd("swayosd-client --brightness lower"),
    { repeating = true }
)

-- Player controls
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl -p playerctld next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl -p playerctld previous"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl -p playerctld play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl -p playerctld play-pause"), { locked = true })

-- Resize the active window
hl.bind(
    "SUPER + ALT + L",
    hl.dsp.window.resize({ x = 40, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + ALT + H",
    hl.dsp.window.resize({ x = -40, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + ALT + K",
    hl.dsp.window.resize({ x = 0, y = -40, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + ALT + J",
    hl.dsp.window.resize({ x = 0, y = 40, relative = true }),
    { repeating = true }
)

hl.bind(
    "SUPER + ALT + right",
    hl.dsp.window.resize({ x = 40, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + ALT + left",
    hl.dsp.window.resize({ x = -40, y = 0, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + ALT + up",
    hl.dsp.window.resize({ x = 0, y = -40, relative = true }),
    { repeating = true }
)
hl.bind(
    "SUPER + ALT + down",
    hl.dsp.window.resize({ x = 0, y = 40, relative = true }),
    { repeating = true }
)

-- Useful window rules

hl.window_rule({
    -- ignore maximize requests from all apps -- usually more convenient this way
    name = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- fix drag-and-drop issues under XWayland
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },

    no_focus = true,
})

-- window rule for hyprland-run
hl.window_rule({
    name = "move-hyprland-run",

    match = { class = "hyprland-run" },

    move = { "20", "monitor_h-120" },
    float = true,
})

-- hl.layer_rule({
--     name = "no_anim_for_selection",
--     match = { namespace = "selection" },
--     no_anim = true,
-- })

hl.layer_rule({
    name = "no_anim_for_hyprpicker",
    match = { namespace = "^(hyprpicker)$" },
    no_anim = true,
})

-- fix for invisible drag windows (they usually have an empty title)
hl.window_rule({
    name = "ue4-drag-empty-fix",
    match = { class = "^(UE4Editor|UnrealEditor)$", title = "^$" },

    no_initial_focus = true,
    no_focus = true,
})

hl.window_rule({
    name = "float-dialect",
    match = { class = "^(app.drey.Dialect)$" },
    float = true,
})

-- pin-screen.sh: the window class starts with desktop-pin, matched by prefix
-- floating + on top; the script sets the exact geometry via hyprctl
hl.window_rule({
    name = "float-desktop-pin",
    match = { class = "^(desktop-pin).*$" },
    float = true,
    pin = true,
})

-- Wayland gives the compositor no "this is a dialog" hint (match.modal reads the
-- XWayland flag only), so dialogs are floated by hand. Everything routed through
-- the portal -- GTK4/Chromium/Electron file choosers -- shares this one class
hl.window_rule({
    name = "float-portal-dialogs",
    match = { class = "^(xdg-desktop-portal-gtk)$" },
    float = true,
})

-- xarchiver builds its file choosers in-process, so they share the app class --
-- nothing tells them apart from the main window, float the whole app
-- spawn under the cursor instead of the monitor centre, clamped to stay on screen
hl.window_rule({
    name = "float-xarchiver",
    match = { class = "^(xarchiver)$" },
    float = true,
    move = {
        "min(max(cursor_x-window_w,0),monitor_w-window_w)",
        "min(max(cursor_y-window_h,0),monitor_h-window_h)",
    },
})

hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "waybar" }, animation = "slide" })
